apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'id.animo.mdocdatatransfer'
version = '0.1.0'

android {
    namespace "id.animo.mdocdatatransfer"
    defaultConfig {
        versionCode 1
        versionName "0.1.0"
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    jvmToolchain(17)
}


repositories {
    maven {
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        content { snapshotsOnly() }
    }
}

dependencies {
    implementation("eu.europa.ec.eudi:eudi-lib-android-iso18013-data-transfer:0.4.0") {
        exclude group: 'org.bouncycastle'
        exclude module: 'bcprov-jdk18on'
    }
    implementation("org.bouncycastle:bcprov-jdk18on") {
        version {
            strictly '1.72'
        }
    }
    implementation "androidx.biometric:biometric-ktx:1.2.0-alpha05"
}
